import { expect, it } from 'vitest';
import { ReviewSession } from '../src/review/session';
import { MockReviewAdapter } from '../src/review/mock-adapter';
import type { InterrogationResult, ReviewAdapter } from '../src/shared/contracts';
const input = {thesis:'ETH is being accumulated by Smart Money, so the market is broadly aligned with my bullish thesis.',symbol:'ETH',lookbackHours:24 as const,mode:'demo' as const,requestId:'one'};
it('ignores a cancelled late response while a newer review runs', async () => {
  const resolves: ((r:InterrogationResult)=>void)[] = [];
  const adapter:ReviewAdapter = { review: () => new Promise(resolve => resolves.push(resolve)) };
  const session = new ReviewSession(adapter);
  const first = session.onPour(input);
  await expect(session.onPour({...input,requestId:'duplicate'})).rejects.toThrow(/already/);
  session.cancel();
  const second = session.onPour({...input,requestId:'two'});
  const fixture = await new MockReviewAdapter(0).review(input);
  resolves[0](fixture);
  await expect(first).rejects.toMatchObject({name:'AbortError'});
  expect(session.getSnapshot().activeRequestId).toBe('two');
  resolves[1]({...fixture,requestId:'two'});
  await second;
  expect(session.getSnapshot().result?.requestId).toBe('two');
  expect(session.getSnapshot().workflowState).toBe('result');
});
it('exposes an error then permits a safe retry', async () => {
  let fail = true;
  const mock = new MockReviewAdapter(0);
  const session = new ReviewSession({review: (value, signal) => fail ? Promise.reject(new Error('Temporary failure')) : mock.review(value,signal)});
  await expect(session.onPour(input)).rejects.toThrow('Temporary failure');
  expect(session.getSnapshot().workflowState).toBe('error');
  expect(session.getSnapshot().activeRequestId).toBeNull();
  fail = false;
  await session.onPour({...input,requestId:'retry'});
  expect(session.getSnapshot().result?.requestId).toBe('retry');
});
